Repository upbound/platform-ref-multi-vault, pull requests merged in 2022-02, with the labels that each got.

#4 Update compositions to allow patches from multiple inputs
  configuration/cluster/definition.yaml
  configuration/cluster/gke/composition.yaml
  configuration/cluster/vault/composition.yaml
  configuration/cluster/vault/definition.yaml
  configuration/crossplane.yaml
  examples/network.yaml
  examples/vaultcluster.yaml
Labels: size/L

#5 Move network configuration into vault-on-gke composition
  configuration/cluster/composition.yaml
  configuration/cluster/definition.yaml
  configuration/cluster/gke/composition.yaml
  configuration/cluster/gke/definition.yaml
  configuration/cluster/gke/network/composition.yaml
  configuration/cluster/gke/network/definition.yaml
  configuration/network/definition.yaml
  examples/network.yaml
  examples/vaultcluster.yaml
Labels: size/L

#7 Update documentation and composition to be consistent with the new name
  README.md
  configuration/cluster/composition.yaml
  configuration/cluster/definition.yaml
  configuration/cluster/gke/composition.yaml
  configuration/cluster/gke/definition.yaml
  configuration/cluster/network/composition.yaml
  configuration/cluster/network/definition.yaml
  configuration/cluster/vault/composition.yaml
  configuration/cluster/vault/definition.yaml
  configuration/crossplane.yaml
  examples/vaultcluster.yaml
Labels: size/L

#10 Add Github workflows to push configuration packages
  .github/workflows/ci.yaml
  .github/workflows/tag.yml
  README.md
Labels: size/M

#11 Fix build & push commands in CI
  .github/workflows/ci.yaml
Labels: size/XS
